name: Trigger auto deployment for my-print-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-print-api-AutoDeployTrigger-9c0b4370-4eb3-4820-a478-f95a1c097697.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYPRINTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYPRINTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYPRINTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.MYPRINTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYPRINTAPI_REGISTRY_PASSWORD }}
          containerAppName: my-print-api
          resourceGroup: RG-MY-PRINT
          imageToBuild: ghcr.io/my-print-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


